ckanext/qdes/blueprint.py

[DDCI-96] Defer commit on bulk update.

---

ckanext/qdes/helpers.py
ckanext/qdes/jobs.py
ckanext/qdes/plugin.py
ckanext/qdes/templates/admin/config.html

https://it-partners.atlassian.net/browse/DDCI-97
- added config fields
- added last run date for the automated report.

[DDCI-97] - added config setting

---

ckanext/qdes/helpers.py
ckanext/qdes/logic/action/get.py
ckanext/qdes/logic/helpers/report_helpers.py

https://it-partners.atlassian.net/browse/DDCI-246
~I have left a comment on slack https://salsadigitalau.slack.com/archives/C0177ASULSG~
~let me know if this still need an update.~

[DDCI-246] - fix missing recommended issue

---

ckanext/qdes/helpers.py
ckanext/qdes/logic/action/get.py

https://it-partners.atlassian.net/browse/DDCI-246

[DDCI-246] - fix filename and contact point

---

ckanext/qdes/templates/organization/member_new.html

https://it-partners.atlassian.net/browse/DDCI-282
this is the ticket I mentioned on slack.
so before it looks like this, 
and after I fix the user variable to pull from the correct variable, 
so on the parent file, the `user` is set outside the blocks, and I am not sure how to change this variable. so what I did here, copy the parent file, and modify the variable.
tested to change the role, it works fine.

[DDCI-282] - load the correct user_dict variable

---

ckanext/qdes/helpers.py

Fix issue with datetime conversion
Hotfix for UAT environment.

[HOTFIX] UAT Review Datasets

---

ckanext/qdes/blueprint.py
ckanext/qdes/helpers.py
ckanext/qdes/plugin.py
ckanext/qdes/templates/admin/api_tokens.html
ckanext/qdes/templates/admin/snippets/api_token_list.html

- Created new 'ckan-admin' blueprint routes for 'api_tokens' and 'api_token_revoke'
- Created new templates 'api_tokens.html' & 'api_token_list.html' to view all user tokens

[DDCI-579] API token management

---

ckanext/qdes/logic/action/get.py

https://it-partners.atlassian.net/browse/DDCI-327

[DDCI-327] - added check for pkg state

---

ckanext/qdes/blueprint.py
ckanext/qdes/plugin.py
ckanext/qdes/templates/admin/config.html
ckanext/qdes/templates/contact_page.html

https://it-partners.atlassian.net/browse/DDCI-547

[DDCI-547] -  added contact

---

ckanext/qdes/cli.py
ckanext/qdes/helpers.py
ckanext/qdes/logic/action/create.py
ckanext/qdes/plugin.py
ckanext/qdes/templates/activity_streams/activity_stream_email_notifications.text

https://it-partners.atlassian.net/browse/DDCI-59
so the `ckan post -c |ckan.ini| /api/action/send_email_notifications` is not working somehow in my local (I have tried to change the .ini file) but the `post` command is missing.
so I created a new job, 
``` ckan -c /app/ckan/default/ckan.ini send-email-notifications```
seems working on locally.

[DDCI-59] - added custom email notification

---

ckanext/qdes/plugin.py
ckanext/qdes/templates/activity_streams/activity_stream_email_notifications.text

https://it-partners.atlassian.net/browse/DDCI-59

[DDCI-59] - changed url link to named route

---

ckanext/qdes/blueprint.py

https://it-partners.atlassian.net/browse/DDCI-430

[DDCI-430] - added defensive coding when dataset is empty

---

ckanext/qdes/blueprint.py

https://it-partners.atlassian.net/browse/DDCI-430

[DDCI-430] - added message when no dataset selected

---

ckanext/qdes/helpers.py
ckanext/qdes/middleware.py
ckanext/qdes/plugin.py
ckanext/qdes/templates/admin/config.html
ckanext/qdes/validators.py

- Added new admin config for 'banner_imageæ
- Added new template helpers:
- get_banner_image
- get_recently_created_datasets
- get_most_popular_datasets
- get_dataset_totals_by_type
- qdes_tracking_enabled
- Added new middleware QdesTrackingMiddleware to fix issue with CKAN TrackingMiddleware
- Added new CKAN config value for 'ckan.qdes.tracking_enabled' to enable QdesTrackingMiddleware

[DDCI-141] Promote-catalogue

---

ckanext/qdes/helpers.py

- Updated 'get_banner_image' to return file upload path or link url

[DDCI-141]

---

ckanext/qdes/helpers.py

- Updated method `get_recently_created_datasets`:
- Will query package table instead of activity table
- Query will filter out deleted and private datasets
- Updated method `get_most_popular_datasets`:
- Updated query to join tracking_summary and package table
- Query will filter out deleted and private datasets
- Removed unesccassary `package_show` action because the query now returns package table data

[DDCI-703]

---

ckanext/qdes/fanstatic/dashboard_reports.js
ckanext/qdes/fanstatic/webassets.yml
ckanext/qdes/templates/user/dashboard_reports.html

- Added JS webasset to remove flash messages on click of the generate button

[DDCI-733]

---

ckanext/qdes/plugin.py
ckanext/qdes/templates/activity_streams/activity_stream_email_notifications.text
ckanext/qdes/templates/emails/body/review_datasets.html
ckanext/qdes/templates/emails/body/review_datasets.txt
ckanext/qdes/templates/emails/subject/review_datasets.txt

https://it-partners.atlassian.net/browse/DDCI-685

[DDCI-685] - updated email wording

---

ckanext/qdes/access/middleware.py

- Locked down all api requests
- All api request require authenticated api key

[DDCI-667]

---

ckanext/qdes/access/helpers.py
ckanext/qdes/access/logic/auth/create.py
ckanext/qdes/access/logic/auth/delete.py
ckanext/qdes/access/logic/auth/update.py
ckanext/qdes/access/templates/organization/edit_base.html

- Updated member auth functions to check if the group is an organisation
- If it is, only allows sysadmin access
- Elsefallback to default auth function

[DDCI-768]

---

ckanext/qdes/blueprint.py
ckanext/qdes/jobs.py

https://it-partners.atlassian.net/browse/DDCI-762

[DDCI-762] - moved review dataset process to job

---

ckanext/qdes/access/logic/auth/get.py
ckanext/qdes/access/plugin.py

Remove api_token_list overridden method

[DDCI-869] Remove api_token_list overridden method

---

ckanext/qdes/helpers.py
ckanext/qdes/plugin.py
ckanext/qdes/templates/user/dashboard_datasets.html
ckanext/qdes/templates/user/read.html

https://it-partners.atlassian.net/browse/DDCI-877
this one is needed, https://github.com/salsadigitalauorg/ckanext-vocabulary-services/pull/29

[DDCI-877] - load user datasets whom current user is the poc

---

ckanext/qdes/logic/action/create.py
ckanext/qdes/logic/action/delete.py
ckanext/qdes/logic/action/get.py
ckanext/qdes/plugin.py

https://it-partners.atlassian.net/browse/DDCI-591
api endpoint `api/3/action/api_token_activity_log`

[DDCI-591] - recorded user token activity

---

ckanext/qdes/helpers.py
ckanext/qdes/templates/user/dashboard_review_datasets.html

Use the position id to filter out the results

[DDCI-777] Show only logged in user's datasets for review

---

ckanext/qdes/helpers.py

https://it-partners.atlassian.net/browse/DDCI-970

[DDCI-970] included private dataset

---

ckanext/qdes/cli.py
ckanext/qdes/jobs.py

Click command for monitoring job

[SUPDESQ-14] jobwork monitor

---

ckanext/qdes/logic/action/get.py

Update qdes_datasets_not_reviewed action with changes in the column names for the report. Column Name is changed to column ID

[SUPDESQ-26] Update column names

---

ckanext/qdes/helpers.py

Rename the download filename for the audit reports

[SUPDESQ-42] Audit reports zip file

---

ckanext/qdes/templates/user/dashboard_reports.html

Change the dropdown text to All

[SUPDESQ-41] Update dropdown text

---

ckanext/qdes/helpers.py

[SUPDESQ-42] Audit reports filename

---

ckanext/qdes/blueprint.py
ckanext/qdes/helpers.py
ckanext/qdes/logic/action/get.py
ckanext/qdes/plugin.py
ckanext/qdes/templates/user/dashboard.html
ckanext/qdes/templates/user/dashboard_follows.html

Add My follows option to the dashboard

[SUPDESQ-50] My follows

---

ckanext/qdes/jobs.py

Use the ENV variable for jobworkier ping check

[SUPDESQ-59] Jobworker monitor ENV variabale

---

ckanext/qdes/helpers.py
ckanext/qdes/jobs.py
ckanext/qdes/logic/action/create.py
ckanext/qdes/logic/action/get.py
ckanext/qdes/logic/helpers/report_helpers.py
ckanext/qdes/plugin.py

Release QDES 1.4.0

---

ckanext/qdes/access/blueprint.py
ckanext/qdes/access/config/qdes_idp.xml
ckanext/qdes/access/helpers.py
ckanext/qdes/access/plugin.py

Using the Saml2Auth interfaces to apply qdes custom logic and to update user organisations

Migrated qdes code from Saml2Auth into this extension

---

ckanext/qdes/access/blueprint.py
ckanext/qdes/access/config/qdes_idp.xml
ckanext/qdes/access/helpers.py
ckanext/qdes/access/plugin.py

* Migrated qdes code from Saml2Auth into this extension Using the Saml2Auth interfaces to apply qdes custom logic and to update user organisations
* Added qdes identity provider metadata xml
* Cleaned up imports
* Refactored logic foy sysadmins

Migrated qdes code from Saml2Auth into this extension (#26)

---

ckanext/qdes/access/blueprint.py
ckanext/qdes/access/config/qdes_idp.xml
ckanext/qdes/access/helpers.py
ckanext/qdes/access/plugin.py

* Migrated qdes code from Saml2Auth into this extension Using the Saml2Auth interfaces to apply qdes custom logic and to update user organisations
* Added qdes identity provider metadata xml
* Cleaned up imports
* Refactored logic foy sysadmins

Migrated qdes code from Saml2Auth into this extension (#26) (#56)

---

ckanext/qdes/cli.py
ckanext/qdes/jobs.py
ckanext/qdes/templates/emails/body/validate_datasets.html
ckanext/qdes/templates/emails/body/validate_datasets.txt
ckanext/qdes/templates/emails/subject/validate_datasets.txt

[SUPDESQ-131](https://salsadigital.atlassian.net/browse/SUPDESQ-131): Weekly validation script for dataset errors
[SUPDESQ-131]: https://salsadigital.atlassian.net/browse/SUPDESQ-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Weekly validation script for dataset errors

---

ckanext/qdes/helpers.py

CKAN 2.11.2 has activity as separate extension, updating the custom code to read the packages using `get_action` instead so that default TrackingSummary will be loaded automatically and fix the custom query to reflect the new extension.

[SUPDESQ-173] fix ext to be compatible with 2.11.2
